AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to create an EC2 instance with a security group and IAM role

Parameters:
  KeyName:
    Description: Name of an existing EC2 keypair for SSH access
    Type: AWS::EC2::KeyPair::KeyName
  VpcId:
    Description: VPC ID where the EC2 instance will be launched
    Type: AWS::EC2::VPC::Id
  SubnetId:
    Description: Subnet ID where the EC2 instance will be launched
    Type: AWS::EC2::Subnet::Id
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t3.micro
      - t3.small
      - t3.medium
    ConstraintDescription: Must be a valid EC2 instance type.

Resources:
  MyIAMRole:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role

  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: EC2BasicAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:Describe*
                  - s3:ListAllMyBuckets
                Resource: "*"

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-0e35ddab05955cf57 
      SubnetId: !Ref SubnetId
      IamInstanceProfile: !Ref MyIAMRole
      SecurityGroupIds:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: MyEC2Instance

Outputs:
  InstanceId:
    Description: Instance ID
    Value: !Ref MyEC2Instance

  PublicIP:
    Description: Public IP address of the instance
    Value: !GetAtt MyEC2Instance.PublicIp

  SecurityGroupId:
    Description: Security Group ID
    Value: !Ref MySecurityGroup

  IAMRole:
    Description: IAM Role ARN
    Value: !GetAtt EC2Role.Arn

  PublicDNS:
    Description: Public DNS name of the instance
    Value: !GetAtt MyEC2Instance.PublicDnsName
